# Site settings
title: Gestão Livre
email: contato@gestaolivre.org
url: http://www.gestaolivre.org/
description: "O software livre para a gestão da sua empresa"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Gestão Livre

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
#  - title: twitter
#    url: https://twitter.com/SBootstrap
#  - title: facebook
#    url:
  #- title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/gestaolivre/gestaolivre

# Build settings
markdown: kramdown
permalink: pretty
